// frontend/src/components/landing/FeaturesSection.tsx
import { motion } from 'framer-motion';
import { 
  DollarSign, 
  Clock, 
  TrendingUp, 
  Users, 
  FileText, 
  Shield 
} from 'lucide-react';

const features = [
  {
    icon: DollarSign,
    title: 'Payroll Management',
    description: 'Automate salary calculations, tax deductions, and direct deposits with precision and compliance.',
    gradient: 'from-emerald-500 to-teal-500',
  },
  {
    icon: Clock,
    title: 'Attendance Tracking',
    description: 'Real-time attendance monitoring with biometric integration and flexible shift management.',
    gradient: 'from-blue-500 to-cyan-500',
  },
  {
    icon: TrendingUp,
    title: 'Performance Reviews',
    description: 'Set goals, track progress, and conduct meaningful performance evaluations effortlessly.',
    gradient: 'from-violet-500 to-purple-500',
  },
  {
    icon: Users,
    title: 'Employee Onboarding',
    description: 'Streamline the onboarding process with automated workflows and document management.',
    gradient: 'from-amber-500 to-orange-500',
  },
  {
    icon: FileText,
    title: 'Leave Management',
    description: 'Handle leave requests, approvals, and balance tracking with a self-service portal.',
    gradient: 'from-rose-500 to-pink-500',
  },
  {
    icon: Shield,
    title: 'Compliance & Security',
    description: 'Stay compliant with labor laws and protect sensitive data with enterprise-grade security.',
    gradient: 'from-indigo-500 to-blue-500',
  },
];

const containerVariants = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.1,
    },
  },
};

const itemVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5 },
  },
};

export function FeaturesSection() {
  return (
    <section id="features" className="py-24 lg:py-32 relative overflow-hidden">
      {/* Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-secondary/20 via-background to-background" />
      
      <div className="container mx-auto px-4 lg:px-8 relative z-10">
        {/* Section Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center max-w-3xl mx-auto mb-16"
        >
          <h2 className="text-3xl sm:text-4xl lg:text-5xl font-display font-bold mb-4">
            Everything you need to{' '}
            <span className="bg-clip-text text-transparent bg-gradient-to-r from-primary to-accent">
              manage your team
            </span>
          </h2>
          <p className="text-lg text-muted-foreground">
            Powerful features designed to simplify HR operations and enhance employee experience.
          </p>
        </motion.div>

        {/* Features Grid */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 lg:gap-8"
        >
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              variants={itemVariants}
              className="group relative"
            >
              <div className="glass-card p-6 lg:p-8 h-full hover-lift cursor-pointer">
                {/* Icon */}
                <div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${feature.gradient} flex items-center justify-center mb-6 group-hover:scale-110 transition-transform duration-300`}>
                  <feature.icon className="h-6 w-6 text-white" />
                </div>
                
                {/* Content */}
                <h3 className="text-xl font-display font-semibold mb-3">
                  {feature.title}
                </h3>
                <p className="text-muted-foreground leading-relaxed">
                  {feature.description}
                </p>

                {/* Hover gradient border */}
                <div className={`absolute inset-0 rounded-xl bg-gradient-to-br ${feature.gradient} opacity-0 group-hover:opacity-10 transition-opacity duration-300 -z-10`} />
              </div>
            </motion.div>
          ))}
        </motion.div>
      </div>
    </section>
  );
}

// frontend/src/app/shared/components/landing/features-section.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Zap, Shield, BarChart3, Clock } from 'lucide-angular';

@Component({
  selector: 'app-features-section',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  template: `
    <section id="features" class="py-24 bg-secondary/10">
      <div class="container mx-auto px-4 lg:px-8">
        <div class="text-center max-w-3xl mx-auto mb-16 animate-fade-in-up">
          <h2 class="text-3xl sm:text-4xl font-display font-bold mb-4">Everything you need to manage your team</h2>
          <p class="text-lg text-muted-foreground">
            Powerful tools to help you streamline HR processes and focus on what matters most—your people.
          </p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          @for (feature of features; track feature.title; let i = $index) {
            <div 
              class="p-8 rounded-2xl bg-card border border-border/50 shadow-soft hover:shadow-glow transition-all duration-300 animate-fade-in-up"
              [style.animation-delay]="0.1 * i + 's'"
            >
              <div class="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-6 text-primary">
                <lucide-icon [img]="feature.icon" class="h-6 w-6" />
              </div>
              <h3 class="text-xl font-bold mb-3 font-display tracking-tight">{{ feature.title }}</h3>
              <p class="text-muted-foreground leading-relaxed">{{ feature.description }}</p>
            </div>
          }
        </div>
      </div>
    </section>
  `,
  styles: [`
    .animate-fade-in-up { animation: fadeInUp 0.5s ease-out forwards; opacity: 0; }
    @keyframes fadeInUp { from { opacity: 0; transform: translateY(20px); } to { opacity: 1; transform: translateY(0); } }
  `]
})
export class FeaturesSectionComponent {
  ZapIcon = Zap;
  ShieldIcon = Shield;
  BarChartIcon = BarChart3;
  ClockIcon = Clock;

  features = [
    { title: 'Fast Onboarding', description: 'Get new hires up and running in minutes with automated workflows.', icon: Zap },
    { title: 'Secure Data', description: 'Enterprise-grade security to keep your employee data safe and compliant.', icon: Shield },
    { title: 'Insightful Analytics', description: 'Make data-driven decisions with real-time HR dashboards.', icon: BarChart3 },
    { title: 'Time Tracking', description: 'Simple attendance and leave management for modern teams.', icon: Clock },
  ];
}
